version: "3.8"

services:
  client:
    image: "pramod90/micro-client:v0.1"
    # volumes:
    #   - data:/data/db  here not need volume
    ports:
      - "3000:3000"

  post:
    image: "pramod90/micro-post:v0.1"
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - client

  comment:
    image: "pramod90/micro-comment:v0.1"
    ports:
      - "4001:4001"
    env_file:
      - ./.env
    depends_on:
      - post
